version: '2'

services:
    logic-test-kiwi:
        image: chalmersrevere/opendlv-logic-test-kiwi-amd64:v0.0.7
        network_mode: "host"
        command: "/usr/bin/opendlv-logic-test-kiwi --cid=111 --freq=30 --frame-id=0"

